version: 2
jobs:
  build:
    docker:
      - image: gcr.io/google_appengine/python
        environment:
          DATABASE_NAME: "appdb"
          DATABASE_USER: "root"
          DATABASE_PASSWD: ""
      - image: circleci/mysql
        environment:
          MYSQL_DATABASE: "appdb"
          MYSQL_USER: "root"
          MYSQL_PASSWORD: ""
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            virtualenv env
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          command: apt-get install libmysqlclient-dev
      - run:
          command: |
            . env/bin/activate
            python manage.py test

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            TAG="0.1.${CIRCLE_BUILD_NUM}"
            docker build -t ferock/sopas:$TAG .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push ferock/sopas:$TAG

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
