version: 2
jobs:
  build:
    docker:
      - image: gcr.io/google_appengine/python
        enviroment:
          DATABASE_NAME: "appdb"
          DATABASE_USER: "appuser"
          DATABASE_PASSWD: "apppw"
      - image: mysql
        enviroment:
          MYSQL_DATABASE: "appdb"
          MYSQL_USER: "appuser"
          MYSQL_PASSWORD: "apppw"
          MYSQL_ROOT_PASSWORD: "apppw"
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: apt-get install libmysqlclient-dev
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
