# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_product_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orden',
            field=models.IntegerField(default=-1),
        ),
    ]
