# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_auto_20170226_1122'),
        ('shipping', '0002_auto_20150604_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleteDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_per_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price per order')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price per item')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Free Shipping')),
                ('countries', models.ManyToManyField(blank=True, to='address.Country', verbose_name='Countries')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'verbose_name': 'Order and Item Charge',
                'verbose_name_plural': 'Order and Item Charges',
            },
        ),
    ]
